    # Publish joint states
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 1000

    panda_arm_controller:
        type: effort_controllers/JointTrajectoryController
        joints:
            - panda_joint1
            - panda_joint2
            - panda_joint3
            - panda_joint4
            - panda_joint5
            - panda_joint6
            - panda_joint7
            
        constraints:
            goal_time: 0.5

        gains:
            panda_joint1: { p: 600, d: 25, i: 0.1, i_clamp: 1000 }
            panda_joint2: { p: 4400, d: 45, i: 4.0, i_clamp: 1000 }
            panda_joint3: { p: 2800, d: 60, i: 1.0, i_clamp: 1000 }
            panda_joint4: { p: 1600, d: 36, i: 0.7, i_clamp: 1000 }
            panda_joint5: { p: 480, d: 14, i: 0.5, i_clamp: 1000 }
            panda_joint6: { p: 140, d: 5, i: 0.02, i_clamp: 1000 }
            panda_joint7: { p: 10, d: 0.05, i: 0.001, i_clamp: 1000 }
        #velocity_ff:
        #    panda_joint1: 1.0
        #    panda_joint2: 1.0
        #    panda_joint3: 1.0
        #    panda_joint4: 1.0
        #    panda_joint5: 1.0
        #    panda_joint6: 1.0
        #    panda_joint7: 1.0

        constraints:
            goal_time: 2.0

        state_publish_rate: 1000
        action_monitor_rate: 100
        stop_trajectory_duration: 0.2

    panda_hand_controller:
        type: effort_controllers/JointTrajectoryController
        joints:
            - panda_finger_joint1
            - panda_finger_joint2
            - panda_probe_cyl_joint

        gains:
            panda_finger_joint1: { p: 20, d: 5.0, i: 0, i_clamp: 1 }
            panda_finger_joint2: { p: 20, d: 5.0, i: 0, i_clamp: 1 }
            panda_probe_cyl_joint: { p: 5, d: 1.0, i: 0, i_clamp: 1 }

        state_publish_rate: 1000
        allow_partial_joints_goal: True
